name: arquivocapivara_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.8.6
  audioplayers: ^6.0.0  # ← mantendo audioplayers

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fundo/fundo.png
    - assets/fundo/fundo-H15.jpeg
    - assets/personagens/Pingo.jpeg
    - assets/videos/videoPingo.mp4
    - assets/videos/videoPingoEsperando.mp4
    - assets/audio/typingText.ogg
    - assets/audio/musicaPingo.ogg
    - assets/fundo/corredor_manacas.jpeg
    - assets/fundo/sala_principal_cap.jpeg
    - assets/personagens/capivarilda_atacada.png
    - assets/fundo/entrada_manacas.jpeg
    - assets/fundo/pegadas.png

  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf